CREATE TABLE PUBLIC.EV_USER (
  ID SERIAL PRIMARY KEY  NOT NULL,
  FULL_NAME VARCHAR(255) NOT NULL ,
  EMAIL VARCHAR(255),
  ID_NUMBER VARCHAR(13),
  AGE INTEGER,
  GENDER VARCHAR(6),
  CREATION_TIMESTAMP TIMESTAMP,
  MODIFICATION_TIMESTAMP TIMESTAMP
)